//! Post-processing: turn the captured transcript into a capability report a
//! human can read without knowing anything about this tool.

use std::collections::BTreeMap;
use std::fmt::Write;

use serde_json::Value;

use crate::capture::{FrameRecord, StepRecord};
use crate::sweep::Findings;

pub fn build(findings: &Findings, steps: &[StepRecord], frames: &[FrameRecord]) -> String {
    let mut m = String::new();
    let _ = writeln!(m, "# FANUC RMI capability report");
    let _ = writeln!(m);
    let _ = writeln!(m, "| | |");
    let _ = writeln!(m, "|---|---|");
    let _ = writeln!(m, "| Controller | `{}` |", findings.addr);
    let _ = writeln!(m, "| Run started | {} |", findings.started_utc);
    let _ = writeln!(m, "| Mode | **{}** |", findings.mode);
    let _ = writeln!(m, "| Exchanges | {} |", steps.len());
    let _ = writeln!(m, "| Raw frames captured | {} |", frames.len());
    let _ = writeln!(m);
    let _ = writeln!(
        m,
        "Generated by `cargo run -p fanuc_probe`. Every row below is backed by the raw JSON in \
         `frames/` and `transcript.ndjson` in this same directory."
    );

    verdict(&mut m, findings, steps);
    controller_section(&mut m, findings);
    groups_section(&mut m, findings, steps);
    configuration_section(&mut m, findings);
    registers_section(&mut m, findings);
    motion_section(&mut m, findings);
    command_matrix(&mut m, steps);
    deserialization_section(&mut m, steps, frames);
    notes_section(&mut m, findings);
    appendix(&mut m, steps);
    m
}

fn verdict(m: &mut String, f: &Findings, steps: &[StepRecord]) {
    let _ = writeln!(m, "\n## Compatibility verdict (meteorite)\n");

    let init = |mask: u8| f.init_attempts.iter().find(|a| a.mask == mask);
    let g1_ok = init(0b01).map(|a| a.status == "ok").unwrap_or(false);
    let g11_ok = init(0b11).map(|a| a.status == "ok").unwrap_or(false);
    let g2_ok = init(0b10).map(|a| a.status == "ok").unwrap_or(false);

    let mut rows: Vec<(String, String)> = Vec::new();
    rows.push((
        "Single-group RMI session (`GroupMask` 0b01)".into(),
        yes_no(g1_ok, init(0b01).and_then(|a| a.error_text.clone())),
    ));
    rows.push((
        "Coordinated arm+positioner session (`GroupMask` 0b11)".into(),
        yes_no(g11_ok, init(0b11).and_then(|a| a.error_text.clone())),
    ));
    rows.push((
        "Positioner-only session (`GroupMask` 0b10)".into(),
        yes_no(g2_ok, init(0b10).and_then(|a| a.error_text.clone())),
    ));
    let g2_read = steps
        .iter()
        .any(|s| s.command == "FRC_ReadJointAngles" && s.label.contains("g2") && s.succeeded());
    rows.push(("Group-2 state is readable (`FRC_ReadJointAngles` group 2)".into(), yes_no(g2_read, None)));
    let reg_ok = f.registers.first().map(|r| r.status == "ok").unwrap_or(false);
    rows.push(("Numeric registers `R[n]` over RMI".into(), yes_no(reg_ok, None)));

    let _ = writeln!(m, "| Capability | Result |");
    let _ = writeln!(m, "|---|---|");
    for (k, v) in rows {
        let _ = writeln!(m, "| {k} | {v} |");
    }
    let _ = writeln!(m);

    let _ = writeln!(m, "**Bottom line:**\n");
    if g11_ok {
        let _ = writeln!(
            m,
            "- This controller ACCEPTS `GroupMask = 0b11`. meteorite's hardcoded 0b11 for a bound \
             positioner is correct here, and coordinated two-group motion packets (`G1`/`G2` blocks) \
             are addressable."
        );
    } else if g1_ok {
        let reason = init(0b11)
            .and_then(|a| a.error_text.clone())
            .unwrap_or_else(|| "see the initialize table".into());
        let _ = writeln!(
            m,
            "- This controller REFUSES `GroupMask = 0b11` ({reason}) but accepts `0b01`. \
             meteorite must NOT hardcode 0b11 for this robot: it should initialize with 0b01 and \
             treat the positioner as read-only (or drive it through a controller-resident TP program). \
             The usual cause is that the controller's `RMI_MOVE` TP program is configured for one \
             motion group only — that is a controller-side configuration change, not a code fix."
        );
    } else {
        let _ = writeln!(
            m,
            "- NO `FRC_Initialize` mask succeeded. Nothing about motion can be concluded; fix the \
             controller state (teach pendant disabled, servos ready, no program selected on the TP) \
             and re-run."
        );
    }
    if g2_ok && !g11_ok {
        let _ = writeln!(
            m,
            "- Group 2 exists and can be reserved on its own, so the positioner IS configured as a \
             motion group — it is the *combination* with Group 1 that this controller rejects."
        );
    }
    if !g2_read {
        let _ = writeln!(
            m,
            "- Group-2 reads did not succeed, which suggests no second motion group is configured \
             on this controller at all."
        );
    }

    let counts = status_counts(steps);
    let _ = writeln!(
        m,
        "- Exchange tally: {} succeeded, {} returned a controller error, {} were unsupported, \
         {} failed to deserialize, {} timed out, {} skipped.",
        counts.get("ok").copied().unwrap_or(0),
        counts.get("controller_error").copied().unwrap_or(0),
        counts.get("unknown_command").copied().unwrap_or(0),
        counts.get("deserialize_failed").copied().unwrap_or(0),
        counts.get("timeout").copied().unwrap_or(0),
        counts.get("skipped").copied().unwrap_or(0),
    );
}

fn yes_no(ok: bool, why: Option<String>) -> String {
    if ok {
        "**YES**".into()
    } else {
        match why {
            Some(w) => format!("**NO** — {w}"),
            None => "**NO**".into(),
        }
    }
}

fn controller_section(m: &mut String, f: &Findings) {
    let _ = writeln!(m, "\n## Controller\n");
    match &f.connect {
        Some(v) => {
            let _ = writeln!(m, "`FRC_Connect` handshake:\n");
            let _ = writeln!(m, "| Field | Value |");
            let _ = writeln!(m, "|---|---|");
            for k in ["MajorVersion", "MinorVersion", "PortNumber", "ErrorID"] {
                if let Some(x) = v.get(k) {
                    let _ = writeln!(m, "| {k} | `{x}` |");
                }
            }
        }
        None => {
            let _ = writeln!(m, "No `FRC_Connect` response was captured.");
        }
    }

    if let Some(s) = &f.status {
        let _ = writeln!(m, "\n`FRC_GetStatus`:\n");
        let _ = writeln!(m, "| Field | Value | Meaning |");
        let _ = writeln!(m, "|---|---|---|");
        let meaning: &[(&str, &str)] = &[
            ("ServoReady", "1 = servos ready; 0 = servo fault or E-stop"),
            ("TPMode", "0 = teach pendant DISABLED (required for RMI); 1 = enabled"),
            ("RMIMotionStatus", "0 = RMI_MOVE not running"),
            ("ProgramStatus", "controller program state"),
            ("SingleStepMode", "0 = continuous"),
            ("NumberUTool", "active UTool number"),
            ("NumberUFrame", "active UFrame number"),
            ("NextSequenceID", "the sequence id the controller expects next"),
            ("OverRide", "speed override %"),
            ("Override", "speed override %"),
            ("ErrorID", "0 = no error"),
        ];
        for (k, why) in meaning {
            if let Some(x) = s.get(*k) {
                let _ = writeln!(m, "| {k} | `{x}` | {why} |");
            }
        }
    }
}

fn groups_section(m: &mut String, f: &Findings, steps: &[StepRecord]) {
    let _ = writeln!(m, "\n## Motion groups\n");
    let _ = writeln!(m, "### `FRC_Initialize` group-mask discovery\n");
    if f.init_attempts.is_empty() {
        let _ = writeln!(m, "Not attempted.");
    } else {
        let _ = writeln!(m, "| GroupMask | What it reserves | Result | ErrorID | Echoed GroupMask |");
        let _ = writeln!(m, "|---|---|---|---|---|");
        for a in &f.init_attempts {
            let _ = writeln!(
                m,
                "| `{}` | {} | {} | {} | {} |",
                a.mask_binary,
                a.meaning,
                status_word(&a.status),
                a.error_text
                    .clone()
                    .or_else(|| a.error_id.filter(|e| *e != 0).map(|e| e.to_string()))
                    .unwrap_or_else(|| "—".into()),
                a.echoed_group_mask.map(|g| g.to_string()).unwrap_or_else(|| "—".into()),
            );
        }
    }
    if let Some(mask) = f.session_mask {
        let _ = writeln!(m, "\nThe probe ran the rest of the sweep on `GroupMask = {mask:#04b}`.");
    }

    let _ = writeln!(m, "\n### Per-group reads\n");
    let _ = writeln!(m, "| Group | Cartesian read | Joint read | UFrame/UTool read |");
    let _ = writeln!(m, "|---|---|---|---|");
    for g in [1u8, 2u8] {
        let ok = |cmd: &str| {
            steps
                .iter()
                .find(|s| s.command == cmd && s.label.ends_with(&format!("g{g}")))
                .map(|s| status_word(&s.status))
                .unwrap_or_else(|| "—".into())
        };
        let _ = writeln!(
            m,
            "| {g} | {} | {} | {} |",
            ok("FRC_ReadCartesianPosition"),
            ok("FRC_ReadJointAngles"),
            ok("FRC_GetUFrameUTool")
        );
    }
    if let Some(j) = &f.group2_joints {
        let _ = writeln!(m, "\nGroup-2 joint payload as returned:\n\n```json\n{}\n```", pretty(j));
    }
}

fn configuration_section(m: &mut String, f: &Findings) {
    let _ = writeln!(m, "\n## Live configuration (used for motion commands)\n");
    let _ = writeln!(
        m,
        "Motion packets echo the Configuration the controller reported for Group 1, rather than a \
         guessed default."
    );
    match &f.active_configuration {
        Some(c) => {
            let _ = writeln!(m, "\n```json\n{}\n```", pretty(c));
        }
        None => {
            let _ = writeln!(m, "\nNot available — `FRC_ReadCartesianPosition` (group 1) did not return a Configuration.");
        }
    }
    if let Some(u) = &f.uframe_utool_g1 {
        let _ = writeln!(m, "\nActive UFrame/UTool (group 1):\n\n```json\n{}\n```", pretty(u));
    }
    if let Some(p) = &f.group1_cartesian {
        let _ = writeln!(m, "\nGroup-1 Cartesian pose at the start of the run:\n\n```json\n{}\n```", pretty(p));
    }
}

fn registers_section(m: &mut String, f: &Findings) {
    let _ = writeln!(m, "\n## Registers\n");
    if f.registers.is_empty() {
        let _ = writeln!(m, "No numeric registers were read.");
    } else {
        let ok: Vec<_> = f.registers.iter().filter(|r| r.status == "ok").collect();
        let _ = writeln!(
            m,
            "`FRC_ReadRegister` swept R[1]..R[{}] — {} readable, {} not.",
            f.registers.iter().map(|r| r.register).max().unwrap_or(0),
            ok.len(),
            f.registers.len() - ok.len()
        );
        if !ok.is_empty() {
            let _ = writeln!(m, "\n| Register | Value |");
            let _ = writeln!(m, "|---|---|");
            for r in ok.iter().take(40) {
                let _ = writeln!(
                    m,
                    "| R[{}] | {} |",
                    r.register,
                    r.value.map(|v| format!("{v}")).unwrap_or_else(|| "—".into())
                );
            }
        }
        let bad: Vec<_> = f.registers.iter().filter(|r| r.status != "ok").collect();
        if !bad.is_empty() {
            let _ = writeln!(
                m,
                "\nUnreadable: {}",
                bad.iter()
                    .map(|r| format!("R[{}] ({})", r.register, r.status))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
    }
    if let Some(w) = &f.register_write {
        let _ = writeln!(m, "\nWrite/restore test:\n\n```json\n{}\n```", pretty(w));
    } else {
        let _ = writeln!(m, "\nNo register write was attempted (pass `--write-register <N>` to test writes; the original value is always restored).");
    }
}

fn motion_section(m: &mut String, f: &Findings) {
    let _ = writeln!(m, "\n## Motion\n");
    let _ = writeln!(
        m,
        "Safety envelope in force: linear ≤ {} mm/s, rotary ≤ {} deg/s, 1 mm linear steps, 1° rotary \
         steps, **no rotary motion on the arm (Group 1) under any flag**.",
        crate::sweep::MAX_LINEAR_SPEED_MM_S,
        crate::sweep::MAX_ROTARY_SPEED_DEG_S
    );
    if !f.motion.attempted {
        let _ = writeln!(
            m,
            "\nNo motion was attempted{}.",
            f.motion
                .abort_reason
                .clone()
                .map(|r| format!(" — {r}"))
                .unwrap_or_else(|| " (read-only run)".into())
        );
        return;
    }

    let _ = writeln!(m, "\nSpeeds used: {} mm/s linear, {} deg/s rotary.", f.motion.linear_speed_mm_s, f.motion.rotary_speed_deg_s);
    let _ = writeln!(m, "\n### Group 1 — linear XYZ only\n");
    let _ = writeln!(m, "| Move | Commanded | Measured | Off by | Result |");
    let _ = writeln!(m, "|---|---|---|---|---|");
    for a in &f.motion.axes {
        let _ = writeln!(
            m,
            "| {} | {:+.3} mm | {} | {} | {} |",
            a.axis,
            a.commanded_mm,
            a.measured_mm.map(|v| format!("{v:+.3} mm")).unwrap_or_else(|| "—".into()),
            a.residual_mm.map(|v| format!("{v:.3} mm")).unwrap_or_else(|| "—".into()),
            pass_or_fail(a.passed, &a.detail)
        );
    }
    if !f.motion.group2.is_empty() {
        let _ = writeln!(m, "\n### Group 2 — positioner rotary\n");
        let _ = writeln!(m, "| Move | Commanded | Measured (from start) | Off by | Result |");
        let _ = writeln!(m, "|---|---|---|---|---|");
        for a in &f.motion.group2 {
            let _ = writeln!(
                m,
                "| {} | {:+.3}° | {} | {} | {} |",
                a.axis,
                a.commanded_mm,
                a.measured_mm.map(|v| format!("{v:+.3}°")).unwrap_or_else(|| "—".into()),
                a.residual_mm.map(|v| format!("{v:.3}°")).unwrap_or_else(|| "—".into()),
                pass_or_fail(a.passed, &a.detail)
            );
        }
        let _ = writeln!(
            m,
            "\n> Caveat for the operator: the JRep speed field is sent as `SpeedType: mmSec` because \
             that is the only unit this library exposes. 0.5 was chosen because it is slow under \
             every plausible controller reading of that field (0.5 mm/s, 0.5 °/s, or 0.5 %). Confirm \
             the observed speed on the real machine before raising it.\n>\n\
             > The packet carries a zero `G1` block (hold the arm) beside the `G2` delta, which is \
             the spec-correct encoding (Operators Manual §2.4.7.1). The probe re-reads the arm's \
             joint angles after every positioner move and stops the sweep if the arm moved at all — \
             a controller that treats the zero block as an absolute target would otherwise drive the \
             arm to its zero pose."
        );
    }
    if let Some(w) = &f.motion.group2_arm_moved {
        let _ = writeln!(m, "\n> **ARM MOTION HAZARD:** {w}");
    }
    if let Some(r) = f.motion.return_residual_mm {
        if r <= 0.35 {
            let _ = writeln!(m, "\nFinal pose vs. start pose: **{r:.3} mm** — the arm returned to where it started.");
        } else {
            let _ = writeln!(
                m,
                "\nFinal pose vs. start pose: **{r:.3} mm** — WARNING, that is outside tolerance. \
                 Compare the raw poses in the appendix before concluding the arm actually moved: \
                 every individual move above was verified in isolation, and some controllers (and \
                 the bundled simulator) recompute the reported Cartesian pose from joint state, \
                 which can shift the *reported* pose without the arm moving."
            );
        }
    }
    if f.motion.aborted {
        let _ = writeln!(
            m,
            "\n**The motion sequence was aborted:** {}",
            f.motion.abort_reason.clone().unwrap_or_default()
        );
    }
}

fn command_matrix(m: &mut String, steps: &[StepRecord]) {
    let _ = writeln!(m, "\n## Command support matrix\n");
    let _ = writeln!(m, "One row per RMI packet the probe exercised.\n");
    let _ = writeln!(m, "| Command | Attempts | Succeeded | Controller error | Unsupported | Deser. failed | Timed out | Worst ErrorID |");
    let _ = writeln!(m, "|---|---|---|---|---|---|---|---|");

    let mut by_cmd: BTreeMap<&str, Vec<&StepRecord>> = BTreeMap::new();
    for s in steps {
        by_cmd.entry(s.command.as_str()).or_default().push(s);
    }
    for (cmd, rows) in by_cmd {
        let count = |st: &str| rows.iter().filter(|r| r.status == st).count();
        let attempts = rows.iter().filter(|r| r.status != "skipped").count();
        let worst = rows
            .iter()
            .filter_map(|r| r.error_text.clone())
            .next()
            .unwrap_or_else(|| "—".into());
        let _ = writeln!(
            m,
            "| `{cmd}` | {attempts} | {} | {} | {} | {} | {} | {worst} |",
            count("ok"),
            count("controller_error"),
            count("unknown_command"),
            count("deserialize_failed"),
            count("timeout"),
        );
    }

    let skipped: Vec<&StepRecord> = steps.iter().filter(|s| s.status == "skipped").collect();
    if !skipped.is_empty() {
        let _ = writeln!(m, "\n### Deliberately not attempted\n");
        for s in skipped {
            let _ = writeln!(
                m,
                "- `{}` — {} ({})",
                s.command,
                s.description,
                s.detail.clone().unwrap_or_default()
            );
        }
    }
}

fn deserialization_section(m: &mut String, steps: &[StepRecord], frames: &[FrameRecord]) {
    let _ = writeln!(m, "\n## Deserialization failures\n");
    let bad: Vec<&FrameRecord> = frames.iter().filter(|f| f.failed_to_deserialize()).collect();
    if bad.is_empty() {
        let _ = writeln!(
            m,
            "None. Every frame in both directions round-tripped through the `fanuc_rmi` types."
        );
    } else {
        let _ = writeln!(
            m,
            "{} frame(s) did not map onto the `fanuc_rmi` types. Each one is reproduced in full \
             below and stored at `frames/<index>-*.json`.\n",
            bad.len()
        );
        for f in bad {
            let _ = writeln!(m, "### Frame {} ({}, step `{}`)\n", f.index, f.direction, f.step);
            let _ = writeln!(m, "serde error:\n\n```\n{}\n```\n", f.typed_error.clone().unwrap_or_default());
            if let Some(n) = &f.driver_note {
                let _ = writeln!(m, "driver note:\n\n```\n{n}\n```\n");
            }
            let _ = writeln!(m, "raw JSON:\n\n```json\n{}\n```\n", f.raw);
        }
    }

    let timeouts: Vec<&StepRecord> = steps.iter().filter(|s| s.status == "timeout").collect();
    if !timeouts.is_empty() {
        let _ = writeln!(m, "### Timed out (no response at all)\n");
        for s in timeouts {
            let _ = writeln!(m, "- `{}` — {}", s.command, s.description);
        }
    }
}

fn notes_section(m: &mut String, f: &Findings) {
    if f.notes.is_empty() {
        return;
    }
    let _ = writeln!(m, "\n## Notes from the run\n");
    for n in &f.notes {
        let _ = writeln!(m, "- {n}");
    }
}

fn appendix(m: &mut String, steps: &[StepRecord]) {
    let _ = writeln!(m, "\n## Appendix — every exchange, in order\n");
    let _ = writeln!(m, "| # | Phase | Command | Result | ms | Description |");
    let _ = writeln!(m, "|---|---|---|---|---|---|");
    for s in steps {
        let _ = writeln!(
            m,
            "| {} | {} | `{}` | {} | {} | {} |",
            s.index,
            s.phase,
            s.command,
            status_word(&s.status),
            s.duration_ms,
            s.description
        );
    }
    let _ = writeln!(
        m,
        "\nFull request/response JSON for each row is in `steps.json` (fields `sent_raw` / \
         `received_raw`) and, frame by frame, in `transcript.ndjson`."
    );
}

fn status_counts(steps: &[StepRecord]) -> BTreeMap<String, usize> {
    let mut c = BTreeMap::new();
    for s in steps {
        *c.entry(s.status.clone()).or_insert(0) += 1;
    }
    c
}

fn status_word(status: &str) -> String {
    match status {
        "ok" => "SUCCEEDED",
        "controller_error" => "FAILED",
        "unknown_command" => "UNSUPPORTED",
        "deserialize_failed" => "FAILED TO DESERIALIZE",
        "timeout" => "TIMED OUT",
        "send_failed" => "SEND FAILED",
        "skipped" => "skipped",
        other => other,
    }
    .to_string()
}

fn pass_or_fail(passed: bool, detail: &Option<String>) -> String {
    if passed {
        "pass".to_string()
    } else {
        format!("**FAIL** {}", detail.clone().unwrap_or_default())
    }
}

fn pretty(v: &Value) -> String {
    serde_json::to_string_pretty(v).unwrap_or_else(|_| v.to_string())
}
